Vagrant.configure("2") do |config|

  config.vm.box = "dummy"

  config.vm.provider :aws do |aws, override|

    aws.access_key_id = "AKIAJS4UZKOR7KWAKE3Q"

    aws.secret_access_key = "Rz8shph0R8EEaUZALpguMFmEZJSr+sn/b/XvVJHs"

    aws.keypair_name = "vagrant"

    aws.region = "us-east-1"

    aws.ami = "ami-7747d01e"

    override.ssh.username = "ubuntu"
    override.ssh.private_key_path = "./vagrant.pem"
    

  end


end
