VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.define "webapp" do |webapp|
       webapp.vm.hostname = "webapp"
       webapp.vm.network :private_network, ip: "192.168.33.10"

       webapp.vm.provision :puppet do |puppet|
         puppet.manifests_path = "puppet/manifests"
         puppet.module_path = "puppet/modules"
         puppet.manifest_file  = "site.pp"
         puppet.options = "--verbose --debug"
      end
  end
end
